# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the course', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Enter a brief description of the course', max_length=1000)),
                ('is_deleted', models.BooleanField(default=False, help_text='Course availability')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='created date of course')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='modified date of course')),
            ],
        ),
    ]
