# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_in_days',
            field=models.IntegerField(default=1, help_text='Duration of course in days'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=100, help_text='Price in dollar of course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Name of the course', max_length=200, unique=True),
        ),
    ]
