# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0003_auto_20180307_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='primary key of stundent enrolled', primary_key=True, serialize=False)),
                ('course_name', models.TextField(help_text='Name of the course student enrolled', max_length=200)),
                ('user_name', models.TextField(help_text='Name of the student enrolled for course', max_length=150)),
                ('is_deleted', models.BooleanField(default=False, help_text='Course availability')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='created date of course')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='modified date of course')),
                ('course_id', models.ForeignKey(help_text='foreign key of course', on_delete=django.db.models.deletion.CASCADE, to='course_app.Course')),
                ('user_id', models.ForeignKey(help_text='foreign key of student', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
