# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_auto_20180310_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcoursemap',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentcoursemap',
            old_name='user_id',
            new_name='user',
        ),
    ]
