# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0006_auto_20180310_0730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcoursemap',
            unique_together=set([('course', 'user')]),
        ),
    ]
